FROM python:3.11-slim
WORKDIR /app
COPY requirements-frontend.txt .
RUN pip install -r requirements-frontend.txt
COPY . .
CMD ["streamlit", "run", "frontend.py", "--server.port=8501", "--server.address=0.0.0.0"]